### PR TITLE
Fix notebook CI testing

### PR DESCRIPTION
**Pull request by mcflugen**
This pull requests fixes our CI testing of the tutorial notebooks.

Some highlights:
* `run_notebook.py` to find and run notebooks.
* `tutorial_template.ipynb` provides a template for new tutorials.
* Testing for Python 2.7 and 3.5 and 3.6 on Mac and Linux.
* `CONTRIBUTING.md` gives a brief outline about how to contribute to the landlab tutorials, including how the write new tutorials.
* Removed `*_unexpanded.ipynb` and `.py` versions of notebooks.

### CODE REVIEW

**Comment by nicgaspar** [comment]
@mcflugen This is looking great. I love the contributing docs and love the emojis - both your use and the description of proper emoji use - had no idea that was even a thing. Should we highlight that this doc exists? Maybe in the README?

And, there should no longer be unexpanded notebooks, right? I found one, so I can just delete it from this branch, right? I also found another empty file that I will boot. Otherwise seems great.

**Comment by mcflugen** [comment]
Thanks. I removed the unexpanded notebook (under `fault_scarp`). If you could remove the empty file, that would be great!

Glad you like the emojis. I went a little overboard. We don't need to follow the emoji usage guidelines but I thought it was fun. It would also make it easier to categorize our commits if we were to make a change log or to skip CI testing for certain cases (like just documentation changes, for example).

**Comment by nicgaspar** [comment]
What about referring to the CONTRIBUTING doc in the README? Do you think people will find it? I may underestimate people.

**Comment by mcflugen** [comment]
That's a good idea.

GitHub is smart enough to see that our repository has a file called `CONTRIBUTING.md` and, when someone creates a pull request or a new issue, will display a link to that document in a nice big box at the top of the page.

**Comment by nicgaspar** [comment]
Oh, well never mind then. I didn't know, but guessed it was something special given the all caps which I know you hate. I will commit.

**Comment by nicgaspar** [comment]
I will wait for tests to finish...

**Pull request merged**
