### PR TITLE
Tutorial of flow__distance utility

### PR DESCRIPTION
**Pull request by Giuseppecipolla95**

### CODE REVIEW

**Comment by nathanlyons** [comment]
@Giuseppecipolla95 This tutorial will be helpful. Two questions before I can conduct a review.

1. Can you resample the dem, nocella.txt to a courser resolution using GIS software, and use this resampled DEM in the tutorial? Doing so will speed up the watershed utility processing time and also reduce the download size of the tutorials (quicker to download tutorials for the users especially those with slower connections). The cell size is 40 m(?) now. Does 100 or 200 m still work for the tutorial? Maybe resampling negatively affects flow routing too much.

2. Tutorial files may be uploaded in uncompressed (not zip) formats. May you please do these things in your tutorial fork so that I can make in line comments in this pull request:
- create a folder, perhaps named, "stream_length_utility"
- add the files "nocella.txt" and "application_of_stream_length_utility.ipynb into the new folder
- delete the "flow length.zip" in your tutorial folder

**Comment by Giuseppecipolla95** [comment]
@nathanlyons I've tried to resample the file 'nocella.txt' to the cell size of 200 but, as you expected, it negatively affected the flow router. However, it worked perfectly setting a cell size equal to 100 m, so the processing time has been reduced. I've also made the changes you had requested regarding the upload of files. Thanks for reviewing my tutorial!

**Review by nathanlyons — CHANGES_REQUESTED** [review]
Nice tutorial. 

I propose this rewording of the introduction:

> This notebook illustrates how to run the stream_length utility on a digital elevation model (DEM) that represents a real basin in Sicily. First, a watershed will be extracted from the input DEM by using the watershed utility. Then, the distances from each node to the watershed's outlet will be obtained with the stream_length utility. Flow is routed using the D8 algorithm.

The graphics backend should be set prior to plotting to ensure that plots are displayed inline. Enter this somewhere before the first ```figure()```
```python
%matplotlib inline
```

Suggested revision to text prior to ln [3]:
> Set the id of the outlet. The value indicated here is the node id of the entire watershed's outlet:

The colorbar in the ln [5] plot can be hidden. The colors may be confusing because only black and white is shown in the plot.
```python
imshow_grid(mg, ws_mask, allow_colorbar=False)
```

In the text prior to ln [7], may you please clarify why the output of the calculate_stream_length utility may not be used directly? (because you are plotting only the watershed and not the entire grid.)

ln [7] can be simplified to:
```python
flow_length = np.zeros(mg.number_of_nodes)
flow_length[ws_mask] = stream__length[ws_mask] - stream__length[outlet_id]
```
- ```mg.number_of_nodes``` rather than ```len(ws_mask)``` more explicitly indicates the grid number of nodes sets the length of the zeros array.
- replacing the for loop with the indexed values speeds up the code
- ```flow_length[i] = 0``` is also not necessary because all nodes were set to zero by the zeros function and then the above line changes the watersheds nodes to values other than zero.

I find it confusing to have variables that are named ```stream__length``` and ```flow_length```. To me, stream length is applicable only to streams nodes (some decision must be made about which nodes are streams) and flow length is the length of simulated flow at every grid node. However, the stream_length utility calculates what I would call flow length. This is just a naming preference. I am not proposing a change. I do think this tutorial should not use the terms interchangeably. I will duplicate this point in the utility pull request for the sake of record keeping.

I propose calling ```flow_length``` here ```stream__length_ws```. 

ln [8] suggested changes:
```python
mg.add_field('node', 'flow_length', flow_length, noclobber=False)
figure()
imshow_grid(mg, mg.at_node['flow_length'], colorbar_label='stream length (m)')
```
- ```noclobber=False``` allows tutorials users to rerun this block without the error ```FieldError: flow_length: already exists```
- ```mg.at_node['flow_length']``` is a better documented way to access field values.
- I assumed the stream length values are in meters. Please correct if this is not the case.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons thanks for the review! I went ahead and I modified my tutorial. Regarding the name of variables, I totally agree with you. Because of we don't now before which nodes are streams and which belong to other elements of the topography (for example hills or mountains), I would call the output of the stream_length utility _flow_length_. Even in the colorbar_label I prefer _flow_length_ instead of _stream_length_ or _stream_length_ws_. 
Do you think it would be better to call the stream_length utility _flow_length_ utility and its masked output _flow_length_ws_?
As you correctly wrote, the output of stream_length utility is in meters.

**Comment by nathanlyons** [comment]
@Giuseppecipolla95 This is looking good to approve. 

You asked:
> Do you think it would be better to call the stream_length utility flow_length utility and its masked output flow_length_ws?

I do think "flow_length" is a more accurate name for the utility. If you agree it is a better name, and are able to change it, I think it is worth it to make it clear. It is up to you.

The tutorial should be merged into the "Next" branch of tutorials because the stream/flow utility will reside in the developer's version until the next Landlab release. The next release is scheduled for June. Until then, we do not want users of the non-developer's version trying to use this utility before it is available in their version.

Before I can merge, may you please change the target of this pull request to "Next"? Instructions are here: https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons Ok, I definitely believe that "flow_length" is the correct name for the utility. Now that we both agree, can I start to convert any "stream_length" to "flow_length"?

**Comment by kbarnhart** [comment]
@Giuseppecipolla95 and @nathanlyons 

Nice work on the tutorial. 

A few other thoughts on the name. 

Looking at the [Landlab Standard Names page](https://github.com/landlab/landlab/wiki/Standard-names) I think that `flow__distance_to_outlet` may be the best option. 

We try to follow the [CSDMS standard naming practices](https://csdms.colorado.edu/wiki/CSDMS_Standard_Names), which gives a template of **object** + two underscores + **quantity**. I should have done this in the first place when making the utility, but instead I focused on just getting some code written. 

The quantity we are representing is the flow of water, which is referred to in landlab as **flow**. The quantity we are calculating is the distance to the outlet. 

Standard names often end up be rather long, so if you want to shorten in, perhaps we should do `flow__distance`. Note the double underscore. 

I do not think that `stream__length_ws` is clear as I don't think `ws` is common enough for people to intuit watershed.

**Comment by Giuseppecipolla95** [comment]
@kbarnhart Ok, for me this is perfect, the name perfectly reflects the final output. Waiting for @nathanlyons response to fix the names in the code.

**Comment by nathanlyons** [comment]
I agree that flow__distance is a better name. @Giuseppecipolla95, please do feel free to change the utility and tutorial to reflect this.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons and @kbarnhart I've changed the name of the utility, tests and tutorial. Now everything should be fixed, shouldn't it?

**Comment by nathanlyons** [comment]
The tutorial looks to be in good order. Next is to understand why the tests are failing. Other recent tutorial pull requests have passed tests, so perhaps your branch or fork needs to be updated. @Giuseppecipolla95, may you please update your branch/fork with ```Next``` then push it?

**Review by nathanlyons — APPROVED** [review]

**Comment by Giuseppecipolla95** [comment]
@nathanlyons By comparing my fork/branch (called Giuseppecipolla95/tutorial, release) with the head fork/branch (landlab/tutorials, next) I had been told that there wasn't anything to compare, so that my fork/branch was up to date. To do so I followed these instructions (https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser).
I can try, if you agree, to create a new pull request with my tutorial and see if the tests fail again. Let me know your opinion.

**Comment by nathanlyons** [comment]
I see several commits in this pull request not associated with the tutorial, as well as many unrelated files in the "Files changed" tab near the top of this pull request window. The only files that should be charged in this pull request are:

- flow__distance_utility/Application of flow__distance utility.ipynb
- flow__distance_utility/nocella_resampled.txt

I suggest removing the commits that related to this tutorial from this pull request. I believe by removing the unrelated commits, the unrelated file changes will also be removed. After this, please push and we can see how the test do.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons I've tried to remove one of the commits that lead to the tests' failure by running the following command lines on my git-bash:
`#Switch to the branch of the pull request`
`git checkout release`
`#Remove the commit b4b821f`
`git rebase -i b4b821f`
Unfortunately I ran into an error:
_fatal: Needed a single revision
invalid upstream 'b4b821f'_
Would you mind giving me some suggestions to cope with what you wrote in your previous comment?
P.s. I've noticed that most of the tests fail because all the Python's versions prior to 3.6 are found in conflict with the 3.6, while the tests done with the 3.6 version were successful. Could this happen because of I use the 3.6 version and there is something new in the code that that is found in conflict with the previous Python's versions?

**Comment by nathanlyons** [comment]
@Giuseppecipolla95 Sorry, I may have led you a little astray. The commits of others' may be fine. I am used to only seeing commits related to given pull requests.

Moments ago, I merged pull request #21 that aims to address the test issues you noted.

I suggest pulling the Next branch, and commit and push your tutorial fork.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons Pulling the Next branch leads to an error: _Pulling is not possible because you have unmerged files._
When I type in my git-bash the command `git status` these are the unmerged files:
image
Could this problem be the cause of the tests' failure? If yes, do you know how to overcome it? I've tried to follow this guide (https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/) but it didn't allow me to navigate into the repository (the first step).
Unfortunately I'm close to the end of my dissertation, so, in this period, I don't have much time to spend to understand how to fix this problem. If you agree I could send you the files and you could upload them. I'm sure that, in this case, the tests should not fail.

**Comment by nathanlyons** [comment]
@Giuseppecipolla95 In your last post, it appears you are looking at the status of the landlab repository. The landlab repository is not relevant for this pull request. So no, the modified files are unrelated to the test failures. Instead, you wish to look at the tutorial repository.

Please ensure that your tutorial fork is up-to-date with ```Next```. Then, do you get similar notices or other notices when running ```git status``` in the directory of your tutorial fork? How about when you try to push your tutorial fork? 

I certainly understand the minimal time you have while nearing the end of dissertation. I understand your replies will be minimal when you are able to respond to my messages here.

**Comment by Giuseppecipolla95** [comment]
@nathanlyons I've compared my forked repository (called Giuseppecipolla95/tutorials) with _next_ branch bearing with the same instructions of my comment I wrote 12 days ago (https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser). I was behind of your commits to install different Python version in separate environments, so I've updated my forked repository and now the tests are in progress. 
Hoping for their success!

**Comment by nathanlyons** [comment]
@Giuseppecipolla95 Success! Thank you for this useful tutorial.

**Pull request merged**
