### PR TITLE
Gt/add notebook on component tips

### PR DESCRIPTION
**Pull request by gregtucker**
New notebook for component authors.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@gregtucker this is really nice. I made some edits and added a few things, let me know what you think. 

I'd also be interested in @SiccarPoint's comments.

**Comment by gregtucker** [comment]
@amanaster2 here's the draft notebook on compo tips. Thanks for taking a look!

**Review by SiccarPoint — APPROVED** [review]
Text looks great! I note that @kbarnhart and I have both just made edits, so they should now be reflected in the commits.

I'm good for this to go when you're ready - pending @amanaster2 's comments of course.

**Comment by adalvis** [comment]
@gregtucker I'll get this reviewed by the end of the week!

**Comment by adalvis** [comment]
@gregtucker I just submitted a pull request with some edits for the notebook (I hope that's what I was supposed to do...) Sorry for the delay. I mostly cleared up some language and got rid of comma splices. Overall, it's a really great notebook, and I definitely learned a few things going through it!

Also, a quick comment: finding the members of the Landlab Team is not easy. I went searching because the Landlab Team is mentioned in the notebook, and I figured others might be curious as to who is on the team if they don't already know. I think I ended up finding it after searching the Wiki a bit. It might be nice to have that list in a more upfront location, but that's just my take :-)

**Pull request merged**
