### PR TITLE
Update testing procedures

### PR DESCRIPTION
**Pull request by kbarnhart**
This is intended to deal with Issue #31 and Issue #32.

It ports the notebook testing over to be based on pytest. 

It also uses a different version of landlab depending on the merge target. 

If the merge target is `release` then the PR test will be based on release, otherwise (merge target `next` or branch test) it will be based on a developer install. 

Local testing indicates that some notebooks fail. 

I'll make a note of which ones do as CI ones fail.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@saisiddu can you tell me the right thing to do in `ecohydrology/cellular_automaton_vegetation_flat_surface/Ecohyd_functions_flat.py`. 

in line 114 
```python
VegType = np.empty([n/55, grid1.number_of_cells], dtype=int)
``` 
yields an error because n/55 is not a float. 

I made a super easy fix
```python
VegType = np.empty([int(n/55), grid1.number_of_cells], dtype=int)
```
that seemed to work but I want to make sure that it is correct.

**Comment by saisiddu** [comment]
@kbarnhart I think your fix is the right one (I would have done the same thing). Should I check anything else? Thanks for fixing the issue.

**Comment by kbarnhart** [comment]
@saisiddu thanks for checking out my fix. I don't think you need to do anything else! thank you!

**Comment by kbarnhart** [comment]
@mcflugen 

some of these tests error with something like:

```
=================================== FAILURES ===================================
____________________________ test_tutorial_template ____________________________
    def test_tutorial_template():
>       nb, errors = _notebook_run(os.path.join(_TEST_DIR, "tutorial_template.ipynb"))
test_notebooks.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_notebooks.py:27: in _notebook_run
    nb = nbformat.read(fout, nbformat.current_nbformat)
../../../miniconda/envs/_testing/lib/python3.5/site-packages/nbformat/__init__.py:141: in read
    return reads(fp.read(), as_version, **kwargs)
../../../miniconda/envs/_testing/lib/python3.5/site-packages/nbformat/__init__.py:74: in reads
    nb = reader.reads(s, **kwargs)
../../../miniconda/envs/_testing/lib/python3.5/site-packages/nbformat/reader.py:58: in reads
    nb_dict = parse_json(s, **kwargs)
../../../miniconda/envs/_testing/lib/python3.5/site-packages/nbformat/reader.py:14: in parse_json
    nb_dict = json.loads(s, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
s = b'{\n "cells": [\n  {\n   "cell_type": "markdown",\n   "metadata": {},\n   "source": [\n    "<a href=\\"http://landlab...thon",\n   "pygments_lexer": "ipython2",\n   "version": "2.7.13"\n  }\n },\n "nbformat": 4,\n "nbformat_minor": 1\n}\n'
encoding = None, cls = None, object_hook = None, parse_float = None
parse_int = None, parse_constant = None, object_pairs_hook = None, kw = {}
    def loads(s, encoding=None, cls=None, object_hook=None, parse_float=None,
            parse_int=None, parse_constant=None, object_pairs_hook=None, **kw):
        """Deserialize ``s`` (a ``str`` instance containing a JSON
        document) to a Python object.
    
        ``object_hook`` is an optional function that will be called with the
        result of any object literal decode (a ``dict``). The return value of
        ``object_hook`` will be used instead of the ``dict``. This feature
        can be used to implement custom decoders (e.g. JSON-RPC class hinting).
    
        ``object_pairs_hook`` is an optional function that will be called with the
        result of any object literal decoded with an ordered list of pairs.  The
        return value of ``object_pairs_hook`` will be used instead of the ``dict``.
        This feature can be used to implement custom decoders that rely on the
        order that the key and value pairs are decoded (for example,
        collections.OrderedDict will remember the order of insertion). If
        ``object_hook`` is also defined, the ``object_pairs_hook`` takes priority.
    
        ``parse_float``, if specified, will be called with the string
        of every JSON float to be decoded. By default this is equivalent to
        float(num_str). This can be used to use another datatype or parser
        for JSON floats (e.g. decimal.Decimal).
    
        ``parse_int``, if specified, will be called with the string
        of every JSON int to be decoded. By default this is equivalent to
        int(num_str). This can be used to use another datatype or parser
        for JSON integers (e.g. float).
    
        ``parse_constant``, if specified, will be called with one of the
        following strings: -Infinity, Infinity, NaN.
        This can be used to raise an exception if invalid JSON numbers
        are encountered.
    
        To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``
        kwarg; otherwise ``JSONDecoder`` is used.
    
        The ``encoding`` argument is ignored and deprecated.
    
        """
        if not isinstance(s, str):
            raise TypeError('the JSON object must be str, not {!r}'.format(
>                               s.__class__.__name__))
E           TypeError: the JSON object must be str, not 'bytes'
../../../miniconda/envs/_testing/lib/python3.5/json/__init__.py:312: TypeError
----------------------------- Captured stderr call -----------------------------
[NbConvertApp] Converting notebook /home/travis/build/landlab/tutorials/tutorial_template.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python
[NbConvertApp] Writing 2333 bytes to /tmp/tmp88cymgjn.ipynb
```

which I *think* means that the call to read the temporary file output where the notebook output was stored failed because the JSON is `bytes` and not `str`. I'd expect this to be a python 2-3 issue. Though looking at the `nbformat` documentation, I think its supposed to deal with this...

Do you have any ideas?

Also, how do you feel about this approach to testing?

**Comment by kbarnhart** [comment]
It looks like this error is a py3.5 version only thing. I'm going to dig into if there are any differences in the package versions between the 3.5 and 3.6 CIs

**Comment by kbarnhart** [comment]
It looks like all packages I can find use the same versions (nbconvert=5.3.1, nbformat=4.4.0, jsonschema=2.6.0) and that the error is originating in the built in json library. 

@mcflugen any ideas?

**Comment by kbarnhart** [comment]
Looks like this passes now that I fixed the py 3.5 issue.

**Comment by kbarnhart** [comment]
@mcflugen I think my recent commit should fix the py 3.6 errors. I'm not sure how to fix the py 3.5 PR errors. 

They all seem to be the same. But I'm not sure how to fix...

Thanks for making all these improvements!

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/travis/miniconda/envs/_testing/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
from __future__ import print_function
%matplotlib inline
------------------
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-a99844d38556> in <module>()
      1 from __future__ import print_function
----> 2 get_ipython().run_line_magic('matplotlib', 'inline')
~/miniconda/envs/_testing/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2129                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2130             with self.builtin_trap:
-> 2131                 result = fn(*args,**kwargs)
   2132             return result
   2133 
<decorator-gen-107> in matplotlib(self, line)
~/miniconda/envs/_testing/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):
~/miniconda/envs/_testing/lib/python3.5/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 
~/miniconda/envs/_testing/lib/python3.5/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3035         """
   3036         from IPython.core import pylabtools as pt
-> 3037         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   3038 
   3039         if gui != 'inline':
~/miniconda/envs/_testing/lib/python3.5/site-packages/IPython/core/pylabtools.py in find_gui_and_backend(gui, gui_select)
    271     """
    272 
--> 273     import matplotlib
    274 
    275     if gui and gui != 'auto':
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in <module>()
   1089 
   1090 # this is the instance used by the matplotlib classes
-> 1091 rcParams = rc_params()
   1092 
   1093 # Don't trigger deprecation warning when just fetching.
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    930     default matplotlib rc file.
    931     """
--> 932     fname = matplotlib_fname()
    933     if not os.path.exists(fname):
    934         # this should never happen, default in mpl-data should always be found
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in matplotlib_fname()
    744         yield os.path.join(get_data_path(), 'matplotlibrc')
    745 
--> 746     for fname in gen_candidates():
    747         if os.path.exists(fname):
    748             st_mode = os.stat(fname).st_mode
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in gen_candidates()
    741             yield matplotlibrc
    742             yield os.path.join(matplotlibrc, 'matplotlibrc')
--> 743         yield os.path.join(get_configdir(), 'matplotlibrc')
    744         yield os.path.join(get_data_path(), 'matplotlibrc')
    745 
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in wrapper()
    411         nonlocal called, ret
    412         if not called:
--> 413             ret = func()
    414             called = True
    415             _log.debug(fmt, ret)
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in get_configdir()
    640     5. A writable directory could not be found or created; return None.
    641     """
--> 642     return _get_config_or_cache_dir(_get_xdg_config_dir())
    643 
    644 
~/miniconda/envs/_testing/lib/python3.5/site-packages/matplotlib/__init__.py in _get_config_or_cache_dir(xdg_base)
    603     configdir = os.environ.get('MPLCONFIGDIR')
    604     if configdir:
--> 605         configdir = Path(configdir).resolve()
    606     elif sys.platform.startswith(('linux', 'freebsd')) and xdg_base:
    607         configdir = Path(xdg_base, "matplotlib")
~/miniconda/envs/_testing/lib/python3.5/pathlib.py in resolve(self)
   1107         if self._closed:
   1108             self._raise_closed()
-> 1109         s = self._flavour.resolve(self)
   1110         if s is None:
   1111             # No symlink resolution => for consistency, raise an error if
~/miniconda/envs/_testing/lib/python3.5/pathlib.py in resolve(self, path)
    328         # which are symlinks.
    329         base = '' if path.is_absolute() else os.getcwd()
--> 330         return _resolve(base, str(path)) or sep
    331 
    332     def is_reserved(self, parts):
~/miniconda/envs/_testing/lib/python3.5/pathlib.py in _resolve(path, rest)
    313                 # Resolve the symbolic link
    314                 try:
--> 315                     target = accessor.readlink(newpath)
    316                 except OSError as e:
    317                     if e.errno != EINVAL:
~/miniconda/envs/_testing/lib/python3.5/pathlib.py in readlink(self, path)
    420     # Helper for resolve()
    421     def readlink(self, path):
--> 422         return os.readlink(path)
    423 
    424 
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/.config/matplotlib'
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/.config/matplotlib'
 test_notebook[/home/travis/build/landlab/tutorials/boundary_conds/set_BCs_from_xy.ipynb] 
tmpdir = local('/tmp/pytest-of-travis/pytest-0/test_notebook__home_travis_bui1')
notebook = '/home/travis/build/landlab/tutorials/boundary_conds/set_BCs_from_xy.ipynb'
    def test_notebook(tmpdir, notebook):
        with tmpdir.as_cwd():
>           nb, errors = _notebook_run(notebook)
test_notebooks.py:71: 
```

**Comment by kbarnhart** [comment]
Arighty. Since this passes, I'm going to merge it.

**Pull request merged**
