### PR TITLE
Create Lithology and LithoLayers Tutorial

### PR DESCRIPTION
**Pull request by kbarnhart**
This tutorial goes along with the PR in the main landlab repository https://github.com/landlab/landlab/pull/674

I'd also appreciate review from @Glader011235 @amforte @byanites and @mwrossi

### CODE REVIEW

**Comment by kbarnhart** [comment]
tagging @mdpiper

this is the tutorial that has my use of [Holoviews](http://holoviews.org).

**Comment by kbarnhart** [comment]
confirmed, this still works with the updated version of the landlab PR

**Review by gregtucker — APPROVED** [review]
The only issue I see is the complexity of the xarray Dataset inits---the syntax is a little intimidating

**Comment by kbarnhart** [comment]
@gregtucker thats a good point. The idea behind HoloViews is that you annotate your data, and then it does things like display the correct name with units etc rather than you having to manually create all the axis labels, etc. 

This is a great idea, but it does mean things like having the big block of xarray creation. 

Do you think that writing some text explaining what is going on would be sufficient to make it less intimidating?

**Pull request merged**
